/* TAREFA #22307 - FELIPE */

ALTER TABLE [EST]
ADD [TavNumGW] SMALLINT    NULL
CREATE NONCLUSTERED INDEX [IEST6] ON [EST] (
      [TavNumGW])
ALTER TABLE [EST]
 ADD CONSTRAINT [IEST6] FOREIGN KEY ( [TavNumGW] ) REFERENCES [TABVEN]([TavNum])

 /* JOSÉ */

  ALTER TABLE [EST]
ADD [EstIseAlug] BIT    NULL

ALTER TABLE [EST]
ADD [EstDtaAltStatus] DATETIME    NULL