USE PRONTO
GO

CREATE PROCEDURE ConcMobPsRealSint 
(
	@DataTrn DATE, 
	@ValorTrn NUMERIC(17,2) OUTPUT
)
AS
BEGIN
	SELECT @ValorTrn = SUM(MovTrnVlr) FROM TRN08PS A
	LEFT JOIN TRN08 B
	ON A.TRN08PSTOKEN = B.TRNTOK AND B.TRN08VanTrnSeq > 0
	LEFT JOIN MovTrn01 C
	ON B.TRN08VanTrnSeq = C.MovTrnVanSeq
	WHERE CONVERT(DATE, A.TRN08PSDATATRANSACAO) = @DataTrn
	AND A.TRN08PSStatus = 1
END
GO

CREATE PROCEDURE ConcMobPsConfSint 
(
	@DataTrn DATE, 
	@ValorTrn NUMERIC(17,2) OUTPUT
)
AS
BEGIN
	SELECT @ValorTrn = SUM(MovTrnVlr) FROM TRN08PS A
	LEFT JOIN TRN08 B
	ON A.TRN08PSTOKEN = B.TRNTOK AND B.TRN08VanTrnSeq > 0
	LEFT JOIN MovTrn01 C
	ON B.TRN08VanTrnSeq = C.MovTrnVanSeq
	WHERE CONVERT(DATE, A.TRN08PSDATATRANSACAO) = @DataTrn
	AND A.TRN08PSStatus = 1
END
GO

CREATE PROCEDURE ConcMobPsComRealSint 
(
	@DataTrn DATE, 
	@ValorTrn NUMERIC(17,2) OUTPUT
)
AS
BEGIN
	SELECT @ValorTrn = SUM(MovTrnVlrLiqEst) FROM TRN08PS A
	LEFT JOIN TRN08 B
	ON A.TRN08PSTOKEN = B.TRNTOK AND B.TRN08VanTrnSeq > 0
	LEFT JOIN MovTrn01 C
	ON B.TRN08VanTrnSeq = C.MovTrnVanSeq
	WHERE CONVERT(DATE, A.TRN08PSDATATRANSACAO) = @DataTrn
	AND A.TRN08PSStatus = 1
END
GO

CREATE PROCEDURE ConcMobPsComConfSint 
(
	@DataTrn DATE, 
	@ValorTrn NUMERIC(17,2) OUTPUT
)
AS
BEGIN
	SELECT @ValorTrn = SUM(MovTrnVlrLiqEst) FROM TRN08PS A
	LEFT JOIN TRN08 B
	ON A.TRN08PSTOKEN = B.TRNTOK AND B.TRN08VanTrnSeq > 0
	LEFT JOIN MovTrn01 C
	ON B.TRN08VanTrnSeq = C.MovTrnVanSeq
	WHERE CONVERT(DATE, A.TRN08PSDATATRANSACAO) = @DataTrn
	AND A.TRN08PSStatus = 1
END
GO