USE PRONTO
GO

--DROP PROCEDURE [dbo].[ConciCessaoInsereLoop]
--GO

CREATE PROCEDURE [dbo].[ConciCessaoInsereLoop](@DATAINI DATE, @DATAFIM DATE)
AS
BEGIN

	DECLARE @DATAFILTRO DATE;
	DECLARE @ITERADOR INT;
	DECLARE @I INT;

	SET @DATAFILTRO = @DATAINI

	SET @ITERADOR = DATEDIFF(DAY, @DATAINI, @DATAFIM);
	SET @I = 0;

	WHILE @I <= @ITERADOR
	BEGIN
	
		EXEC CONCICESSAOINSERE @DATAFILTRO;
		SET @DATAFILTRO = DATEADD(DAY, 1, @DATAFILTRO)
		SET @I = @I + 1;

	END

END

GO