USE SmartPagamentos
CREATE TABLE [RtCessaoBen] (
  [RtCessaoBenId]            DECIMAL(18)    NOT NULL    IDENTITY ( 1 , 1 ),
  [RtCessaoBenCessaoId]      DECIMAL(10)    NULL,
  [RtCessaoBenEstCod]        INT    NULL,
  [RtCessaoBenEstNome]       VARCHAR(100)    NULL,
  [RtCessaoBenEstSeg]        VARCHAR(40)    NULL,
  [RtCessaoBenEstCpfCnpj]    VARCHAR(15)    NULL,
  [RtCessaoBenOriEstCod]     INT    NULL,
  [RtCessaoBenOriEstNome]    VARCHAR(100)    NULL,
  [RtCessaoBenOriEstCpfCnpj] VARCHAR(15)    NULL,
  [RtCessaoBenDataCad]       DATETIME    NULL,
  [RtCessaoBenStatusDesc]    VARCHAR(20)    NULL,
  [RtCessaoBenParcela]       SMALLINT    NULL,
  [RtCessaoBenValor]         DECIMAL(17,2)    NULL,
  [RtCessaoBenTipo]          VARCHAR(40)    NULL,
  [RtCessaoBenNF]            VARCHAR(128)    NULL,
  [RtCessaoBenValorNF]       DECIMAL(17,2)    NULL,
  [RtCessaoBenDataEmi]       DATETIME    NULL,
  [RtCessaoBenDistri]        VARCHAR(128)    NULL,
  [RtCessaoBenFilial]        VARCHAR(128)    NULL,
  [RtCessaoBenDataTrn]       DATETIME    NULL,
  [RtCessaoBenDataLiqLan]    DATETIME    NULL,
  [RtCessaoBenTipoLan]       VARCHAR(40)    NULL,
  [RtCessaoBenAutCod]        VARCHAR(10)    NULL,
  [RtCessaoBenNsu]           DECIMAL(18)    NULL,
  [RtCessaoBenDetValor]      DECIMAL(17,2)    NULL,
  [RtCessaoBenDataInc]       DATETIME    NULL,
  [RtCessaoBenGuid]          VARCHAR(100)    NULL,
     PRIMARY KEY ( [RtCessaoBenId] ))