USE SmartPagamentos
CREATE TABLE [RtCessaoOri] (
  [RtCessaoOriId]            DECIMAL(18)    NOT NULL    IDENTITY ( 1 , 1 ),
  [RtCessaoOriCessaoId]      DECIMAL(10)    NULL,
  [RtCessaoOriEstCod]        INT    NULL,
  [RtCessaoOriEstNome]       VARCHAR(100)    NULL,
  [RtCessaoOriEstSeg]        VARCHAR(40)    NULL,
  [RtCessaoOriEstCpfCnpj]    VARCHAR(15)    NULL,
  [RtCessaoOriBenEstCod]     INT    NULL,
  [RtCessaoOriBenEstNome]    VARCHAR(100)    NULL,
  [RtCessaoOriBenEstCpfCnpj] VARCHAR(15)    NULL,
  [RtCessaoOriDataCad]       DATETIME    NULL,
  [RtCessaoOriStatusDesc]    VARCHAR(20)    NULL,
  [RtCessaoOriParcela]       SMALLINT    NULL,
  [RtCessaoOriValor]         DECIMAL(17,2)    NULL,
  [RtCessaoOriTipo]          VARCHAR(40)    NULL,
  [RtCessaoOriNF]            VARCHAR(128)    NULL,
  [RtCessaoOriValorNF]       DECIMAL(17,2)    NULL,
  [RtCessaoOriDataEmi]       DATETIME    NULL,
  [RtCessaoOriDistri]        VARCHAR(128)    NULL,
  [RtCessaoOriFilial]        VARCHAR(128)    NULL,
  [RtCessaoOriDataTrn]       DATETIME    NULL,
  [RtCessaoOriDataLiqLan]    DATETIME    NULL,
  [RtCessaoOriTipoLan]       VARCHAR(40)    NULL,
  [RtCessaoOriAutCod]        VARCHAR(10)    NULL,
  [RtCessaoOriNsu]           DECIMAL(18)    NULL,
  [RtCessaoOriDetValor]      DECIMAL(17,2)    NULL,
  [RtCessaoOriDataInc]       DATETIME    NULL,
  [RtCessaoOriGuid]          VARCHAR(100)    NULL,
     PRIMARY KEY ( [RtCessaoOriId] ))