ALTER TABLE [EST]
ADD [TavNumPS] SMALLINT    NULL,
    [EstUsaPS] BIT    NULL
CREATE NONCLUSTERED INDEX [IEST7] ON [EST] (
      [TavNumPS])
ALTER TABLE [EST]
 ADD CONSTRAINT [IEST7] FOREIGN KEY ( [TavNumPS] ) REFERENCES [TABVEN]([TavNum])