CREATE TABLE [LancamentosBoaVista] (
  [LanBoaVistaId]            DECIMAL(12) IDENTITY ( 1 , 1 )   NOT NULL,
  [LanBoaVistaDtaVen]        DATETIME    NOT NULL,
  [LanBoaVistaHraVen]        DATETIME    NOT NULL,
  [LanBoaVistaDtaCre]        DATETIME    NOT NULL,
  [LanBoaVistaNsu]           DECIMAL(18)    NOT NULL,
  [LanBoaVistaAut]           DECIMAL(14)    NOT NULL,
  [LanBoaVistaPlano]         INT    NOT NULL,
  [LanBoaVistaBan]           SMALLINT    NOT NULL,
  [LanBoaVistaProd]          CHAR(3)    NOT NULL,
  [LanBoaVistaVlrVen]        DECIMAL(17,2)    NOT NULL,
  [LanBoaVistaVlrBru]        DECIMAL(17,2)    NOT NULL,
  [LanBoaVistaCodEst]        CHAR(20)    NOT NULL,
  [LanBoaVistaVlrLiq]        DECIMAL(17,2)    NOT NULL,
  [LanBoaVistaStatus]        CHAR(2)    NOT NULL,
  [LanBoaVistaModCap]        CHAR(2)    NOT NULL,
  [LanBoaVistaParc]          SMALLINT    NOT NULL,
  [LanBoaVistaVlrTax]        DECIMAL(17,2)    NOT NULL,
  [LanBoaVistaAge]           SMALLINT    NOT NULL,
  [LanBoaVistaBanco]         SMALLINT    NOT NULL,
  [LanBoaVistaConta]         CHAR(20)    NOT NULL,
  [LanBoaVistaStatusEnviado] SMALLINT    NOT NULL,
  [LanBoaVistaJsonUpl]       VARCHAR(MAX)    NULL,
  [LanBoaVistaJsonResp]      VARCHAR(MAX)    NULL,
     PRIMARY KEY ( [LanBoaVistaId] ))