use --[todos]

ALTER TABLE [POS_PLANO]
ADD [PosPlaProp] CHAR(1)    NOT NULL CONSTRAINT PosPlaPropPOS_PLANO_DEFAULT DEFAULT ''

ALTER TABLE [POS_PLANO]
DROP CONSTRAINT PosPlaPropPOS_PLANO_DEFAULT

UPDATE POS_PLANO SET PosPlaProp = 'A'